import type { ServiceIntakeSummary } from "@/lib/types/service-intake";

function line(label: string, value: string) {
  return `${label}: ${value}`;
}

export function renderBookingIntakeEmailText(summary: ServiceIntakeSummary): string {
  const files =
    summary.uploadedFiles.length > 0
      ? summary.uploadedFiles.map((f) => `  - ${f.fileName} (${f.category})`).join("\n")
      : "  (none)";

  return [
    "DANA AUTO CENTRE — NEW BOOKING INTAKE",
    "",
    line("Customer", summary.customerName),
    line("Phone", summary.customerPhone),
    line("Registration", summary.registration),
    line("Vehicle", summary.vehicle ?? "—"),
    "",
    "BOOKING SLOT",
    line("Service", summary.bookingSlot.service),
    line("Date", summary.bookingSlot.preferredDate),
    line("Time", summary.bookingSlot.preferredTime),
    "",
    "VEHICLE REPORT",
    line("Symptoms", summary.symptoms),
    line("Possible causes", summary.possibleCauses.join(", ") || "—"),
    line("Indicative range", summary.estimatedRange ?? "—"),
    line("Urgency", summary.urgency),
    line("Severity", summary.severity ?? "—"),
    line("Callback window", summary.callbackAvailability ?? "—"),
    "",
    "UPLOADS",
    files,
    "",
    "— Generated by Dana Auto Centre intake (not sent automatically yet)",
  ].join("\n");
}

export function renderBookingIntakeEmailHtml(summary: ServiceIntakeSummary): string {
  const causes = summary.possibleCauses.map((c) => `<li>${c}</li>`).join("");
  const uploads = summary.uploadedFiles
    .map((f) => `<li>${f.fileName} <span style="color:#888">(${f.category})</span></li>`)
    .join("");

  return `<!DOCTYPE html>
<html>
<body style="font-family:system-ui,sans-serif;background:#0a0a0a;color:#e5e5e5;padding:24px">
  <h1 style="color:#d4a63c;font-size:18px">New booking intake</h1>
  <table style="width:100%;border-collapse:collapse;margin:16px 0">
    <tr><td style="padding:6px 0;color:#888">Customer</td><td>${summary.customerName}</td></tr>
    <tr><td style="padding:6px 0;color:#888">Phone</td><td>${summary.customerPhone}</td></tr>
    <tr><td style="padding:6px 0;color:#888">Registration</td><td><strong>${summary.registration}</strong></td></tr>
    <tr><td style="padding:6px 0;color:#888">Vehicle</td><td>${summary.vehicle ?? "—"}</td></tr>
  </table>
  <h2 style="font-size:14px;color:#d4a63c">Slot</h2>
  <p>${summary.bookingSlot.service} · ${summary.bookingSlot.preferredDate} at ${summary.bookingSlot.preferredTime}</p>
  <h2 style="font-size:14px;color:#d4a63c">Symptoms</h2>
  <p>${summary.symptoms}</p>
  <ul>${causes}</ul>
  <p><strong>Indicative range:</strong> ${summary.estimatedRange ?? "—"} (not a fixed quote)</p>
  <p><strong>Urgency:</strong> ${summary.urgency} · <strong>Callback:</strong> ${summary.callbackAvailability ?? "—"}</p>
  <h2 style="font-size:14px;color:#d4a63c">Uploads</h2>
  <ul>${uploads || "<li>None</li>"}</ul>
</body>
</html>`;
}
